name: grass-bridges
channels:
  - openalea3
  - conda-forge
channel_priority: strict
dependencies:
  # Scientific
  - python
  - pip
  - pytest
  - scipy
  - numpy
  - pyyaml
  - numba
  - openpyxl
  - pandas
  - salib
  - xarray
  - netcdf4
  - dask
  - pint
  - trimesh
  
  # Openalea
  - openalea.mtg
  - openalea.deploy
  - openalea.lpy
  - openalea.caribu
  - openalea.astk
  - openalea.plantgl

  # Visuals
  - pyvista
  - imageio
  - imageio-ffmpeg
  - matplotlib
  - brokenaxes
  - mesalib<25.1 # otherwise compatibility issues with mesalib
  - "vtk>=9.3.1=*osmesa*"
  
  # For RhizoSoil cmf
  # let pip install the rest using pyproject.toml (if you are okay with conda/pip mix)
  - pip:
      - -e .."[doc]"
