name: grass-bridges
channels:
  - openalea3
  - conda-forge
dependencies:
  # Scientific
  - python
  - pip
  - pytest
  - scipy
  - numpy
  - pyyaml
  - numba
  - openpyxl
  - pandas
  - salib
  - xarray
  - netcdf4
  - dask
  - pint
  - trimesh
  
  # Openalea
  - openalea.mtg
  - openalea.lpy
  - openalea.caribu
  - openalea.astk
  - openalea.plantgl

  # Visuals
  - pyvista
  - imageio
  - imageio-ffmpeg
  - matplotlib
  - brokenaxes
  - "vtk>=9.3.1=*osmesa*"   # [linux]
  - mesalib<25.1            # [linux]
  - vtk>=9.3.1              # [osx]
  - vtk>=9.3.1              # [win]
  
  # For RhizoSoil cmf TODO: fails on mac
  - pip:
      - cmf

platforms:
  - linux-64
  - osx-64
  - osx-arm64
  - win-64
